// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../spiffs.h"
#include "../../nvs.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_login = NULL;
lv_obj_t * ui_zhanghao = NULL;
lv_obj_t * ui_mima = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_loginbtu1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_registerbtu1 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_tongyi = NULL;
lv_obj_t * ui_jizhu = NULL;
lv_obj_t * ui_Keyboard1 = NULL;
lv_obj_t * ui_managebtu1 = NULL;
lv_obj_t * ui_Label8 = NULL;
bool is_remeber = false;

// event funtions
void ui_event_zhanghao(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard1,  ui_zhanghao);
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_mima(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard1,  ui_mima);
    }
}

void ui_event_loginbtu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // 获取账号和密码
        const char *account = lv_textarea_get_text(ui_zhanghao);
        const char *password = lv_textarea_get_text(ui_mima);

        // 检查账号和密码是否匹配
        if (!check_account(account, password)) {
            // 处理保存失败的情况,显示一个错误消息框
            show_message_box("错误","账号或密码错误,请重试!");
        }
        else{
            // 验证成功：根据should_remember_password决定是否保存
            if(is_remeber)
            {
                save_text_to_nvs("acc", account);
                save_text_to_nvs("pwd", password);
            }
            lv_textarea_set_text(ui_mima,"");
            lv_textarea_set_text(ui_zhanghao,"");
            //lv_obj_invalidate(ui_mima);
            //lv_obj_invalidate(ui_zhanghao);
            _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
        }
    }
}

void ui_event_registerbtu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        lv_textarea_set_text(ui_mima,"");
        //lv_obj_invalidate(ui_mima);
        _ui_screen_change(&ui_Screen2, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen2_screen_init);
    }
}

void ui_event_Keyboard1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_managebtu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        load_accounts_to_list();
        _ui_screen_change(&ui_Screen4, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen4_screen_init);
    }
}

void ui_event_tongyi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED)
    {
        bool is_checked = lv_obj_has_state(ui_tongyi, LV_STATE_CHECKED);
        if(is_checked)
        {
            lv_obj_clear_state(ui_loginbtu1, LV_STATE_DISABLED);
        }
        else
        {
            lv_obj_add_state(ui_loginbtu1, LV_STATE_DISABLED);
        }
    }
}

void ui_event_jizhu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED)
    {
        is_remeber = lv_obj_has_state(ui_jizhu, LV_STATE_CHECKED);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_login = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_login, 300);
    lv_obj_set_height(ui_login, 400);
    lv_obj_set_x(ui_login, 0);
    lv_obj_set_y(ui_login, -20);
    lv_obj_set_align(ui_login, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_login, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_login, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_login, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_zhanghao = lv_textarea_create(ui_login);
    lv_obj_set_width(ui_zhanghao, 150);
    lv_obj_set_height(ui_zhanghao, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_zhanghao, 0);
    lv_obj_set_y(ui_zhanghao, -70);
    lv_obj_set_align(ui_zhanghao, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_zhanghao, "账号");
    lv_textarea_set_one_line(ui_zhanghao, true);
    lv_obj_set_style_text_font(ui_zhanghao, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mima = lv_textarea_create(ui_login);
    lv_obj_set_width(ui_mima, 150);
    lv_obj_set_height(ui_mima, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_mima, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_mima, "密码");
    lv_textarea_set_one_line(ui_mima, true);
    lv_textarea_set_password_mode(ui_mima, true);
    lv_obj_set_style_text_font(ui_mima, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_login);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 0);
    lv_obj_set_y(ui_Label1, -140);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "登录界面");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_loginbtu1 = lv_btn_create(ui_login);
    lv_obj_set_width(ui_loginbtu1, 80);
    lv_obj_set_height(ui_loginbtu1, 40);
    lv_obj_set_x(ui_loginbtu1, -60);
    lv_obj_set_y(ui_loginbtu1, 140);
    lv_obj_set_align(ui_loginbtu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_loginbtu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_loginbtu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_state(ui_loginbtu1,LV_STATE_DISABLED);

    ui_Label2 = lv_label_create(ui_loginbtu1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "登录");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_registerbtu1 = lv_btn_create(ui_login);
    lv_obj_set_width(ui_registerbtu1, 80);
    lv_obj_set_height(ui_registerbtu1, 40);
    lv_obj_set_x(ui_registerbtu1, 60);
    lv_obj_set_y(ui_registerbtu1, 140);
    lv_obj_set_align(ui_registerbtu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_registerbtu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_registerbtu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_registerbtu1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "注册");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_tongyi = lv_checkbox_create(ui_login);
    lv_checkbox_set_text(ui_tongyi, "同意协议");
    lv_obj_set_width(ui_tongyi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tongyi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tongyi, 0);
    lv_obj_set_y(ui_tongyi, 45);
    lv_obj_set_align(ui_tongyi, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_tongyi, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_tongyi, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_jizhu = lv_checkbox_create(ui_login);
    lv_checkbox_set_text(ui_jizhu, "记住密码");
    lv_obj_set_width(ui_jizhu, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_jizhu, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_jizhu, 0);
    lv_obj_set_y(ui_jizhu, 85);
    lv_obj_set_align(ui_jizhu, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_jizhu, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_jizhu, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Keyboard1 = lv_keyboard_create(ui_Screen1);
    lv_obj_set_width(ui_Keyboard1, 800);
    lv_obj_set_height(ui_Keyboard1, 120);
    lv_obj_set_x(ui_Keyboard1, 0);
    lv_obj_set_y(ui_Keyboard1, 150);
    lv_obj_set_align(ui_Keyboard1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard1, LV_OBJ_FLAG_HIDDEN);     /// Flags

    ui_managebtu1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_managebtu1, 80);
    lv_obj_set_height(ui_managebtu1, 40);
    lv_obj_set_x(ui_managebtu1, 350);
    lv_obj_set_y(ui_managebtu1, -200);
    lv_obj_set_align(ui_managebtu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_managebtu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_managebtu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_managebtu1);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "账号管理");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    char account[MAX_ACCOUNT_LENGTH] = {0};
    char password[MAX_PASSWORD_LENGTH] = {0};
    if(read_text_from_nvs(account, MAX_ACCOUNT_LENGTH, "acc") == ESP_OK)
    {
        if(read_text_from_nvs(password, MAX_PASSWORD_LENGTH, "pwd") == ESP_OK)
        {
            lv_textarea_set_text(ui_zhanghao, account);
            lv_textarea_set_text(ui_mima, password);
            lv_obj_add_state(ui_jizhu, LV_STATE_CHECKED); 
        }
    }

    lv_obj_add_event_cb(ui_zhanghao, ui_event_zhanghao, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mima, ui_event_mima, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_loginbtu1, ui_event_loginbtu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_registerbtu1, ui_event_registerbtu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard1, ui_event_Keyboard1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_managebtu1, ui_event_managebtu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_tongyi, ui_event_tongyi, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_jizhu, ui_event_jizhu, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_login = NULL;
    ui_zhanghao = NULL;
    ui_mima = NULL;
    ui_Label1 = NULL;
    ui_loginbtu1 = NULL;
    ui_Label2 = NULL;
    ui_registerbtu1 = NULL;
    ui_Label3 = NULL;
    ui_tongyi = NULL;
    ui_jizhu = NULL;
    ui_Keyboard1 = NULL;
    ui_managebtu1 = NULL;
    ui_Label8 = NULL;

}
