// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../spiffs.h"
#include "../../nvs.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_exitbtu2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_deletebtu1 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_AccountList = NULL;

// 当前选中的账号和列表项
lv_obj_t * selected_item = NULL;
char selected_account[MAX_ACCOUNT_LENGTH] = "";
static lv_style_t style_selected;  // 选中样式

// 初始化选中样式
void init_selected_style() {
    lv_style_init(&style_selected);
    lv_style_set_bg_color(&style_selected, lv_color_hex(0x337ab7));  // 蓝色背景
    lv_style_set_text_color(&style_selected, lv_color_hex(0xffffff));  // 白色文字
}

// 列表项点击事件处理
void list_item_click_event(lv_event_t * e) {
    lv_obj_t * item = lv_event_get_target(e);
    
    // 清除之前选中项的样式
    if (selected_item) {
        lv_obj_remove_style(selected_item, &style_selected, LV_PART_MAIN);
    }
    
    // 设置当前选中项样式
    selected_item = item;
    lv_obj_add_style(item, &style_selected, LV_PART_MAIN);
    
    // 提取选中的账号
    const char * item_text = lv_list_get_btn_text(ui_AccountList, item);
    if (item_text) {
        strncpy(selected_account, item_text, strcspn(item_text, ","));
        selected_account[strcspn(item_text, ",")] = '\0';
    }
}

// 直接删除账号（无确认对话框）
void delete_btn_click_event(lv_event_t * e) {
    if (!selected_item || !selected_account[0]) {
        show_message_box("提示", "请先选择一个账号");
        return;
    }
    
    // 直接删除账号，不显示确认对话框
    delete_account_from_file(selected_account);
    load_accounts_to_list();
    
    // 重置选中状态
    selected_item = NULL;
    selected_account[0] = '\0';
    
    show_message_box("成功", "账号已删除");
}

// 从文件加载账号到列表
void load_accounts_to_list() {
    // 清空列表
    if (ui_AccountList) {
        lv_obj_clean(ui_AccountList);
    }
    
    // 打开账号文件
    FILE * file = fopen(FILE_PATH, "r");
    if (!file) {
        // 文件不存在或无法打开，添加空提示
        lv_obj_t *empty_text = lv_list_add_text(ui_AccountList, "暂无账号");
        lv_obj_set_style_text_font(empty_text, &ui_font_Font1, LV_PART_MAIN);
        return;
    }
    
    char line[MAX_ACCOUNT_LENGTH + MAX_PASSWORD_LENGTH + 2];
    while (fgets(line, sizeof(line), file)) {
        // 去除换行符
        line[strcspn(line, "\n")] = '\0';
        
        // 添加到列表
        lv_obj_t * item = lv_list_add_btn(ui_AccountList, NULL, line);
        lv_obj_add_event_cb(item, list_item_click_event, LV_EVENT_CLICKED, NULL);
    }
    
    fclose(file);
    
    // 如果列表为空，显示提示
    if (lv_obj_get_child_cnt(ui_AccountList) == 0) {
        lv_obj_t *empty_text = lv_list_add_text(ui_AccountList, "暂无账号");
        lv_obj_set_style_text_font(empty_text, &ui_font_Font1, LV_PART_MAIN);
    }
}

// 从文件中删除账号
void delete_account_from_file(const char * account) {
    FILE * src = fopen(FILE_PATH, "r");
    FILE * temp = fopen("/spiffs/temp.txt", "w");
    
    if (!src || !temp) {
        ESP_LOGE("SPIFFS", "无法打开文件");
        if (src) fclose(src);
        if (temp) fclose(temp);
        return;
    }
    
    char line[MAX_ACCOUNT_LENGTH + MAX_PASSWORD_LENGTH + 2];
    while (fgets(line, sizeof(line), src)) {
        char existing_account[MAX_ACCOUNT_LENGTH];
        sscanf(line, "%[^,],%*s", existing_account);
        
        // 如果不是要删除的账号，则写入临时文件
        if (strcmp(existing_account, account) != 0) {
            fputs(line, temp);
        }
    }
    
    fclose(src);
    fclose(temp);
    
    // 删除原文件并将临时文件重命名
    remove(FILE_PATH);
    rename("/spiffs/temp.txt", FILE_PATH);

    delete_save_account("acc");
    delete_save_account("pwd");
}

// 退出按钮事件
void ui_event_exitbtu2(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        char account[MAX_ACCOUNT_LENGTH] = {0};
        char password[MAX_PASSWORD_LENGTH] = {0};
        if(read_text_from_nvs(account, MAX_ACCOUNT_LENGTH, "acc") == ESP_OK)
        {
            if(read_text_from_nvs(password, MAX_PASSWORD_LENGTH, "pwd") == ESP_OK)
            {
                lv_textarea_set_text(ui_zhanghao, account);
                lv_textarea_set_text(ui_mima, password);
                lv_obj_add_state(ui_jizhu, LV_STATE_CHECKED); 
            }
        }
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

// 初始化账号管理界面
void ui_Screen4_screen_init(void) {
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_exitbtu2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_exitbtu2, 80);
    lv_obj_set_height(ui_exitbtu2, 40);
    lv_obj_set_x(ui_exitbtu2, 350);
    lv_obj_set_y(ui_exitbtu2, -200);
    lv_obj_set_align(ui_exitbtu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_exitbtu2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_exitbtu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_exitbtu2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "退出");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -200);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "账号管理界面");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deletebtu1 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_deletebtu1, 80);
    lv_obj_set_height(ui_deletebtu1, 40);
    lv_obj_set_x(ui_deletebtu1, 350);
    lv_obj_set_y(ui_deletebtu1, 200);
    lv_obj_set_align(ui_deletebtu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deletebtu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_deletebtu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_deletebtu1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "删除");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 创建账号列表
    init_selected_style();
    ui_AccountList = lv_list_create(ui_Screen4);
    lv_obj_set_size(ui_AccountList, 300, 300);  // 设置列表大小
    lv_obj_align(ui_AccountList, LV_ALIGN_CENTER, 0, 0);  // 居中对齐
    
    // 设置列表样式
    lv_obj_set_style_bg_color(ui_AccountList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AccountList, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AccountList, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 加载账号到列表
    load_accounts_to_list();
    
    // 添加事件回调
    lv_obj_add_event_cb(ui_exitbtu2, ui_event_exitbtu2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_deletebtu1, delete_btn_click_event, LV_EVENT_CLICKED, NULL);
}

// 销毁界面
void ui_Screen4_screen_destroy(void) {
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_exitbtu2 = NULL;
    ui_Label10 = NULL;
    ui_Label9 = NULL;
    ui_deletebtu1 = NULL;
    ui_Label11 = NULL;
    ui_AccountList = NULL;
    selected_item = NULL;
}