// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../spiffs.h"
#include "../../nvs.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_register = NULL;
lv_obj_t * ui_shuruzhanghao = NULL;
lv_obj_t * ui_shurumima = NULL;
lv_obj_t * ui_querenmima = NULL;
lv_obj_t * ui_registerbtu2 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_backbtu1 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Keyboard2 = NULL;

// event funtions
void ui_event_shuruzhanghao(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_shuruzhanghao);
    }
}

void ui_event_shurumima(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_keyboard_set_target(ui_Keyboard2,  ui_shurumima);
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

void ui_event_querenmima(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Keyboard2,  ui_querenmima);
    }
}

void ui_event_registerbtu2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        const char *account = lv_textarea_get_text(ui_shuruzhanghao);
        const char *input_password = lv_textarea_get_text(ui_shurumima);
        const char *confirm_password = lv_textarea_get_text(ui_querenmima);

        // 检查账号是否为空
        if (account == NULL || strlen(account) == 0) {
            show_message_box("错误", "账号不能为空!");
            return;
        }

        // 检查密码是否为空
        if (input_password == NULL || strlen(input_password) == 0) {
            show_message_box("错误", "密码不能为空!");
            return;
        }

        // 检查两次输入的密码是否相同
        if (strcmp(input_password, confirm_password) != 0) {
            show_message_box("错误", "密码不一致,请重新输入!");
            lv_textarea_set_text(ui_querenmima,"");
            //lv_obj_invalidate(ui_querenmima);
            return;
        }

        // 检查文件中是否已经存在相同的账户
        if (check_account(account,NULL)) {
            show_message_box("错误", "该账号已存在,请更换账号!");
            lv_textarea_set_text(ui_shuruzhanghao,"");
            //lv_obj_invalidate(ui_shuruzhanghao);
            return;
        }

        // 保存账号密码到文件
        save_account(account, input_password);

        // 调试：打印所有账号密码（实际发布时可删除）
        print_all_accounts();

        // 显示注册成功消息框
        show_message_box("成功", "注册成功!");

        // 清除文本框内容
        lv_textarea_set_text(ui_shuruzhanghao, "");
        lv_textarea_set_text(ui_shurumima, "");
        lv_textarea_set_text(ui_querenmima, "");
        
        // 刷新文本框显示
        //lv_obj_invalidate(ui_shuruzhanghao);
        //lv_obj_invalidate(ui_shurumima);
        //lv_obj_invalidate(ui_querenmima);

        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_backbtu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // 清除文本框内容
        lv_textarea_set_text(ui_shuruzhanghao, "");
        lv_textarea_set_text(ui_shurumima, "");
        lv_textarea_set_text(ui_querenmima, "");
        
        // 刷新文本框显示
        //lv_obj_invalidate(ui_shuruzhanghao);
        //lv_obj_invalidate(ui_shurumima);
        //lv_obj_invalidate(ui_querenmima);

        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

void ui_event_Keyboard2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_register = lv_obj_create(ui_Screen2);
    lv_obj_set_width(ui_register, 300);
    lv_obj_set_height(ui_register, 400);
    lv_obj_set_x(ui_register, 0);
    lv_obj_set_y(ui_register, -20);
    lv_obj_set_align(ui_register, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_register, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_register, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_register, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shuruzhanghao = lv_textarea_create(ui_register);
    lv_obj_set_width(ui_shuruzhanghao, 150);
    lv_obj_set_height(ui_shuruzhanghao, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_shuruzhanghao, 0);
    lv_obj_set_y(ui_shuruzhanghao, -70);
    lv_obj_set_align(ui_shuruzhanghao, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_shuruzhanghao, "输入账号");
    lv_textarea_set_one_line(ui_shuruzhanghao, true);
    lv_obj_set_style_text_font(ui_shuruzhanghao, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_shurumima = lv_textarea_create(ui_register);
    lv_obj_set_width(ui_shurumima, 150);
    lv_obj_set_height(ui_shurumima, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_shurumima, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_shurumima, "输入密码");
    lv_textarea_set_one_line(ui_shurumima, true);
    lv_textarea_set_password_mode(ui_shurumima, true);
    lv_obj_set_style_text_font(ui_shurumima, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_querenmima = lv_textarea_create(ui_register);
    lv_obj_set_width(ui_querenmima, 150);
    lv_obj_set_height(ui_querenmima, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_querenmima, 0);
    lv_obj_set_y(ui_querenmima, 70);
    lv_obj_set_align(ui_querenmima, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_querenmima, "确认密码");
    lv_textarea_set_one_line(ui_querenmima, true);
    lv_textarea_set_password_mode(ui_querenmima, true);
    lv_obj_set_style_text_font(ui_querenmima, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_registerbtu2 = lv_btn_create(ui_register);
    lv_obj_set_width(ui_registerbtu2, 80);
    lv_obj_set_height(ui_registerbtu2, 40);
    lv_obj_set_x(ui_registerbtu2, 60);
    lv_obj_set_y(ui_registerbtu2, 140);
    lv_obj_set_align(ui_registerbtu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_registerbtu2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_registerbtu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label5 = lv_label_create(ui_registerbtu2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "注册");
    lv_obj_set_style_text_font(ui_Label5, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label7 = lv_label_create(ui_register);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 0);
    lv_obj_set_y(ui_Label7, -140);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "注册界面");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_backbtu1 = lv_btn_create(ui_register);
    lv_obj_set_width(ui_backbtu1, 80);
    lv_obj_set_height(ui_backbtu1, 40);
    lv_obj_set_x(ui_backbtu1, -60);
    lv_obj_set_y(ui_backbtu1, 140);
    lv_obj_set_align(ui_backbtu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_backbtu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_backbtu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_backbtu1, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label6 = lv_label_create(ui_backbtu1);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "返回");

    ui_Keyboard2 = lv_keyboard_create(ui_Screen2);
    lv_obj_set_width(ui_Keyboard2, 800);
    lv_obj_set_height(ui_Keyboard2, 120);
    lv_obj_set_x(ui_Keyboard2, 0);
    lv_obj_set_y(ui_Keyboard2, 150);
    lv_obj_set_align(ui_Keyboard2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Keyboard2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_add_event_cb(ui_shuruzhanghao, ui_event_shuruzhanghao, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_shurumima, ui_event_shurumima, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_querenmima, ui_event_querenmima, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_registerbtu2, ui_event_registerbtu2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_backbtu1, ui_event_backbtu1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Keyboard2, ui_event_Keyboard2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_register = NULL;
    ui_shuruzhanghao = NULL;
    ui_shurumima = NULL;
    ui_querenmima = NULL;
    ui_registerbtu2 = NULL;
    ui_Label5 = NULL;
    ui_Label7 = NULL;
    ui_backbtu1 = NULL;
    ui_Label6 = NULL;
    ui_Keyboard2 = NULL;

}
