// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN2_H
#define UI_SCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen2
extern void ui_Screen2_screen_init(void);
extern void ui_Screen2_screen_destroy(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_register;
extern void ui_event_shuruzhanghao(lv_event_t * e);
extern lv_obj_t * ui_shuruzhanghao;
extern void ui_event_shurumima(lv_event_t * e);
extern lv_obj_t * ui_shurumima;
extern void ui_event_querenmima(lv_event_t * e);
extern lv_obj_t * ui_querenmima;
extern void ui_event_registerbtu2(lv_event_t * e);
extern lv_obj_t * ui_registerbtu2;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label7;
extern void ui_event_backbtu1(lv_event_t * e);
extern lv_obj_t * ui_backbtu1;
extern lv_obj_t * ui_Label6;
extern void ui_event_Keyboard2(lv_event_t * e);
extern lv_obj_t * ui_Keyboard2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

