// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../spiffs.h"
#include "../../nvs.h"
#include "../../lvgl_port.h"
#include "../../wifi_sync.h"

lv_obj_t * ui_Screen5 = NULL;
lv_obj_t * ui_exitbtu3 = NULL;
lv_obj_t * ui_Label12 = NULL;
lv_obj_t * ui_label_cursor_size = NULL;
lv_obj_t * ui_slider_cursor_size = NULL;
lv_obj_t * ui_label_screen_timeout = NULL;     // 熄屏时间标签
lv_obj_t * ui_dropdown_screen_timeout = NULL;   // 熄屏时间下拉选择

// 光标大小范围
#define CURSOR_SIZE_MIN     8     // 最小光标尺寸(像素)
#define CURSOR_SIZE_MAX     48    // 最大光标尺寸(像素)
#define CURSOR_SIZE_DEFAULT 16    // 默认光标尺寸(与 ui_init 中保持一致)

// 从 SPIFFS 加载光标大小(返回 ESP_OK 表示成功读取)
static esp_err_t load_cursor_size(int *size)
{
    if (size == NULL) return ESP_ERR_INVALID_ARG;
    FILE *fp = fopen("/spiffs/cursor_size.txt", "r");
    if (fp == NULL) {
        *size = CURSOR_SIZE_DEFAULT;
        return ESP_ERR_NOT_FOUND;
    }
    char buf[16] = {0};
    if (fgets(buf, sizeof(buf), fp) != NULL) {
        *size = atoi(buf);
        if (*size < CURSOR_SIZE_MIN) *size = CURSOR_SIZE_MIN;
        if (*size > CURSOR_SIZE_MAX) *size = CURSOR_SIZE_MAX;
        fclose(fp);
        return ESP_OK;
    }
    fclose(fp);
    *size = CURSOR_SIZE_DEFAULT;
    return ESP_FAIL;
}

// 保存光标大小到 SPIFFS
static void save_cursor_size(int size)
{
    FILE *fp = fopen("/spiffs/cursor_size.txt", "w");
    if (fp == NULL) {
        return;
    }
    fprintf(fp, "%d", size);
    fclose(fp);
}

// 应用光标大小:直接修改 ui_cursor 的尺寸并更新位置(保持中心点不变)
static void apply_cursor_size(int size)
{
    if (ui_cursor == NULL) return;
    // 保存当前中心点(光标左上角坐标 + 半边长)
    lv_coord_t cx = lv_obj_get_x(ui_cursor) + lv_obj_get_width(ui_cursor) / 2;
    lv_coord_t cy = lv_obj_get_y(ui_cursor) + lv_obj_get_height(ui_cursor) / 2;
    // 设置新尺寸
    lv_obj_set_size(ui_cursor, size, size);
    // 重新定位,让中心点保持不变
    lv_obj_set_pos(ui_cursor, cx - size / 2, cy - size / 2);
}

// 光标大小 Slider 回调:实时更新光标尺寸
static void slider_cursor_size_cb(lv_event_t * e)
{
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    // 把 slider 值映射到光标尺寸范围(线性映射 0..100 -> MIN..MAX)
    int size = CURSOR_SIZE_MIN + (val * (CURSOR_SIZE_MAX - CURSOR_SIZE_MIN)) / 100;
    apply_cursor_size(size);
    // 滑动时只实时更新光标,不写 SPIFFS(释放时再保存,见下面的 RELEASED 回调)
}

// Slider 释放时保存光标大小到 SPIFFS
static void slider_cursor_size_released_cb(lv_event_t * e)
{
    lv_obj_t * slider = lv_event_get_target(e);
    int val = lv_slider_get_value(slider);
    int size = CURSOR_SIZE_MIN + (val * (CURSOR_SIZE_MAX - CURSOR_SIZE_MIN)) / 100;
    save_cursor_size(size);
}

// 熄屏时间 Dropdown 回调:选择后立即保存并应用
static void dropdown_screen_timeout_cb(lv_event_t * e)
{
    lv_obj_t * dd = lv_event_get_target(e);
    // 获取当前选中项的值(10/20/30)
    char buf[8] = {0};
    lv_dropdown_get_selected_str(dd, buf, sizeof(buf));
    int seconds = atoi(buf);
    // 保存到 SPIFFS
    screen_timeout_save(seconds);
    // 立即应用到 lvgl_port 的熄屏定时器
    lvgl_port_set_screen_timeout(seconds);
}

// 退出按钮事件:返回桌面(界面3)
void ui_event_exitbtu3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen3_screen_init);
    }
}

// 初始化设置界面
void ui_Screen5_screen_init(void)
{
    ui_Screen5 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen5, LV_OBJ_FLAG_SCROLLABLE);

    // 退出按钮(右上角)
    ui_exitbtu3 = lv_btn_create(ui_Screen5);
    lv_obj_set_width(ui_exitbtu3, 80);
    lv_obj_set_height(ui_exitbtu3, 40);
    lv_obj_align(ui_exitbtu3, LV_ALIGN_TOP_RIGHT, -12, 12);
    lv_obj_add_flag(ui_exitbtu3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_exitbtu3, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_exitbtu3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_exitbtu3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label12 = lv_label_create(ui_exitbtu3);
    lv_obj_set_width(ui_Label12, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_Label12, LV_SIZE_CONTENT);
    lv_obj_set_align(ui_Label12, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label12, "退出");
    lv_obj_set_style_text_color(ui_Label12, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label12, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_exitbtu3, ui_event_exitbtu3, LV_EVENT_ALL, NULL);

    // 标题
    lv_obj_t * title = lv_label_create(ui_Screen5);
    lv_obj_set_width(title, LV_SIZE_CONTENT);
    lv_obj_set_height(title, LV_SIZE_CONTENT);
    lv_obj_align(title, LV_ALIGN_TOP_MID, 0, 20);
    lv_label_set_text(title, "系统设置");
    lv_obj_set_style_text_font(title, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 第一行:光标大小(左边标签,右边 Slider)
    ui_label_cursor_size = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_label_cursor_size, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_label_cursor_size, LV_SIZE_CONTENT);
    lv_obj_align(ui_label_cursor_size, LV_ALIGN_TOP_LEFT, 40, 100);
    lv_label_set_text(ui_label_cursor_size, "光标大小");
    lv_obj_set_style_text_font(ui_label_cursor_size, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 光标大小 Slider(右边)
    ui_slider_cursor_size = lv_slider_create(ui_Screen5);
    lv_obj_set_width(ui_slider_cursor_size, 300);
    lv_obj_align(ui_slider_cursor_size, LV_ALIGN_TOP_LEFT, 200, 108);
    lv_slider_set_range(ui_slider_cursor_size, 0, 100);
    lv_slider_set_mode(ui_slider_cursor_size, LV_SLIDER_MODE_NORMAL);

    // 从 SPIFFS 读取上次保存的光标大小,设置 Slider 初始值
    int saved_size = CURSOR_SIZE_DEFAULT;
    load_cursor_size(&saved_size);
    // 反向映射:光标尺寸 -> slider 值
    int init_val = (saved_size - CURSOR_SIZE_MIN) * 100 / (CURSOR_SIZE_MAX - CURSOR_SIZE_MIN);
    lv_slider_set_value(ui_slider_cursor_size, init_val, LV_ANIM_OFF);

    // 注册 Slider 事件:拖动时实时更新光标大小,释放时保存到 SPIFFS
    lv_obj_add_event_cb(ui_slider_cursor_size, slider_cursor_size_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_slider_cursor_size, slider_cursor_size_released_cb, LV_EVENT_RELEASED, NULL);

    // 初始化时立即应用一次保存的光标大小(确保进入设置界面后光标尺寸与保存值一致)
    apply_cursor_size(saved_size);

    // 第二行:熄屏时间(左边标签,右边 Dropdown)
    ui_label_screen_timeout = lv_label_create(ui_Screen5);
    lv_obj_set_width(ui_label_screen_timeout, LV_SIZE_CONTENT);
    lv_obj_set_height(ui_label_screen_timeout, LV_SIZE_CONTENT);
    lv_obj_align(ui_label_screen_timeout, LV_ALIGN_TOP_LEFT, 40, 180);
    lv_label_set_text(ui_label_screen_timeout, "熄屏时间");
    lv_obj_set_style_text_font(ui_label_screen_timeout, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 熄屏时间 Dropdown(右边)
    ui_dropdown_screen_timeout = lv_dropdown_create(ui_Screen5);
    lv_obj_set_width(ui_dropdown_screen_timeout, 150);
    lv_obj_align(ui_dropdown_screen_timeout, LV_ALIGN_TOP_LEFT, 200, 170);
    lv_dropdown_set_options(ui_dropdown_screen_timeout, "10\n20\n30");
    lv_obj_set_style_text_font(ui_dropdown_screen_timeout, &ui_font_Font1, LV_PART_ITEMS);

    // 从 SPIFFS 读取上次保存的熄屏时间,设置 Dropdown 初始选中项
    int saved_timeout = screen_timeout_load();
    int sel_idx = 0;  // 默认选第一项(10s)
    if (saved_timeout == 10) sel_idx = 0;
    else if (saved_timeout == 20) sel_idx = 1;
    else if (saved_timeout == 30) sel_idx = 2;
    lv_dropdown_set_selected(ui_dropdown_screen_timeout, sel_idx);

    // 初始化界面时，把读取出来的超时直接应用到底层
    lvgl_port_set_screen_timeout(saved_timeout);

    // 注册 Dropdown 事件:选择后保存并应用
    lv_obj_add_event_cb(ui_dropdown_screen_timeout, dropdown_screen_timeout_cb, LV_EVENT_VALUE_CHANGED, NULL);
}

// 销毁设置界面
void ui_Screen5_screen_destroy(void)
{
    if(ui_Screen5) lv_obj_del(ui_Screen5);

    // NULL screen variables
    ui_Screen5 = NULL;
    ui_exitbtu3 = NULL;
    ui_Label12 = NULL;
    ui_label_cursor_size = NULL;
    ui_slider_cursor_size = NULL;
    ui_label_screen_timeout = NULL;
    ui_dropdown_screen_timeout = NULL;
}
