// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN5_H
#define UI_SCREEN5_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen5
extern void ui_Screen5_screen_init(void);
extern void ui_Screen5_screen_destroy(void);
extern lv_obj_t * ui_Screen5;
extern void ui_event_exitbtu3(lv_event_t * e);
extern lv_obj_t * ui_exitbtu3;
extern lv_obj_t * ui_Label12;
extern lv_obj_t * ui_label_cursor_size;
extern lv_obj_t * ui_slider_cursor_size;
extern lv_obj_t * ui_label_screen_timeout;
extern lv_obj_t * ui_dropdown_screen_timeout;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
