// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../spiffs.h"
#include "../../nvs.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_exitbtu1 = NULL;
lv_obj_t * ui_Label4 = NULL;
// event funtions
void ui_event_exitbtu1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        char account[MAX_ACCOUNT_LENGTH] = {0};
        char password[MAX_PASSWORD_LENGTH] = {0};
        if(read_text_from_nvs(account, MAX_ACCOUNT_LENGTH, "acc") == ESP_OK)
        {
            if(read_text_from_nvs(password, MAX_PASSWORD_LENGTH, "pwd") == ESP_OK)
            {
                lv_textarea_set_text(ui_zhanghao, account);
                lv_textarea_set_text(ui_mima, password);
                lv_obj_add_state(ui_jizhu, LV_STATE_CHECKED); 
            }
        }
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_img_src(ui_Screen3, &ui_img_1984903667, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_exitbtu1 = lv_btn_create(ui_Screen3);
    lv_obj_set_width(ui_exitbtu1, 80);
    lv_obj_set_height(ui_exitbtu1, 40);
    lv_obj_set_x(ui_exitbtu1, 350);
    lv_obj_set_y(ui_exitbtu1, -200);
    lv_obj_set_align(ui_exitbtu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_exitbtu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_exitbtu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_exitbtu1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_exitbtu1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label4 = lv_label_create(ui_exitbtu1);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "退出");
    lv_obj_set_style_text_color(ui_Label4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label4, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_exitbtu1, ui_event_exitbtu1, LV_EVENT_ALL, NULL);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_exitbtu1 = NULL;
    ui_Label4 = NULL;

}
