// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "../../spiffs.h"
#include "../../nvs.h"
#include "../../buzzer.h"          // 蜂鸣器驱动
#include <stdlib.h>
#include <string.h>

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_exitbtu2 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_deletebtu1 = NULL;
lv_obj_t * ui_Label11 = NULL;
lv_obj_t * ui_AccountList = NULL;

// 当前选中的账号和列表项
lv_obj_t * selected_item = NULL;
char selected_account[MAX_ACCOUNT_LENGTH] = "";
static lv_style_t style_selected;  // 选中样式

// 初始化选中样式
void init_selected_style() {
    lv_style_init(&style_selected);
    lv_style_set_bg_color(&style_selected, lv_color_hex(0x337ab7));  // 蓝色背景
    lv_style_set_text_color(&style_selected, lv_color_hex(0xffffff));  // 白色文字
}

// 列表项点击事件处理（使用 user_data 获取账号名）
void list_item_click_event(lv_event_t * e) {
    lv_obj_t * item = lv_event_get_target(e);
    const char * acc = (const char *)lv_obj_get_user_data(item);
    if (!acc) {
        // 若 user_data 为空，回退到按钮文本（但不应发生）
        acc = lv_list_get_btn_text(ui_AccountList, item);
        if (!acc) return;
    }
    
    // 清除之前选中项的样式（先确保对象有效）
    if (selected_item) {
        // 安全起见，检查 selected_item 是否仍然在列表中（尝试获取其父对象）
        // 但更可靠的方法是在列表刷新时重置 selected_item
        lv_obj_remove_style(selected_item, &style_selected, LV_PART_MAIN);
    }
    
    // 设置当前选中项样式
    selected_item = item;
    lv_obj_add_style(item, &style_selected, LV_PART_MAIN);
    
    // 安全拷贝账号名
    strncpy(selected_account, acc, MAX_ACCOUNT_LENGTH - 1);
    selected_account[MAX_ACCOUNT_LENGTH - 1] = '\0';
}

// 删除选中的账号
void delete_btn_click_event(lv_event_t * e) {
    if (!selected_item || !selected_account[0]) {
        show_message_box("提示", "请先选择一个账号");
        return;
    }
    
    // 真正执行删除，并按实际结果给提示
    // (以前无论删没删掉都提示"账号已删除"，把失败伪装成了成功)
    bool ok = delete_account_from_file(selected_account);
    load_accounts_to_list();
    
    // 重置选中状态（load_accounts_to_list 中已重置，此处可省略）
    selected_item = NULL;
    selected_account[0] = '\0';
    
    // 蜂鸣器响一声
    buzzer_beep();
    
    if (ok) {
        show_message_box("成功", "账号已删除");
    } else {
        show_message_box("错误", "该账号不存在!");
    }
}

// 从文件加载账号到列表
void load_accounts_to_list() {
    // ---- 关键修复：重置选中状态，避免野指针 ----
    selected_item = NULL;
    selected_account[0] = '\0';

    // 清空列表
    if (ui_AccountList) {
        // 先释放所有按钮的 user_data
        uint32_t cnt = lv_obj_get_child_cnt(ui_AccountList);
        for (uint32_t i = 0; i < cnt; i++) {
            lv_obj_t * child = lv_obj_get_child(ui_AccountList, i);
            void * data = lv_obj_get_user_data(child);
            if (data) {
                lv_mem_free(data);
                lv_obj_set_user_data(child, NULL);
            }
        }
        lv_obj_clean(ui_AccountList);
    }
    
    // 打开账号文件
    FILE * file = fopen(FILE_PATH, "r");
    if (!file) {
        // 文件不存在或无法打开，添加空提示
        lv_obj_t *empty_text = lv_list_add_text(ui_AccountList, "暂无账号");
        lv_obj_set_style_text_font(empty_text, &ui_font_Font1, LV_PART_MAIN);
        return;
    }
    
    char line[MAX_ACCOUNT_LENGTH + MAX_PASSWORD_LENGTH + 2];
    while (fgets(line, sizeof(line), file)) {
        // 只取这一行里逗号之前的"账号"部分。
        // 【为什么必须这样做】文件里每行是"账号,密码"，而删除时要拿这个字符串
        // 去和文件里的账号做 strcmp 比对。如果这里存的是整行
        // ("账号,密码")，那么 delete_account_from_file() 里
        // "账号" 与 "账号,密码" 永远不相等 → 每一行都会被原样保留 →
        // 表现为"提示账号已删除，但账号还在"。这正是之前删除失效的原因。
        // 顺带也解决了另一个问题：列表里不该把密码显示出来。
        char name_only[MAX_ACCOUNT_LENGTH] = {0};
        const char *comma = strchr(line, ',');
        size_t name_len = comma ? (size_t)(comma - line) : strcspn(line, "\r\n");
        if (name_len >= MAX_ACCOUNT_LENGTH) {
            name_len = MAX_ACCOUNT_LENGTH - 1;   // 防御：账号异常超长时截断
        }
        memcpy(name_only, line, name_len);
        name_only[name_len] = '\0';

        if (name_only[0] == '\0') {
            continue;                            // 跳过空行等格式异常的行
        }

        // 添加到列表(只放账号名，不显示密码)
        lv_obj_t * item = lv_list_add_btn(ui_AccountList, NULL, name_only);
        // 复制账号名到 user_data（便于安全获取）
        char *acc_copy = (char *)lv_mem_alloc(strlen(name_only) + 1);
        if (acc_copy) {
            strcpy(acc_copy, name_only);
            lv_obj_set_user_data(item, acc_copy);
        }
        lv_obj_add_event_cb(item, list_item_click_event, LV_EVENT_CLICKED, NULL);
    }
    
    fclose(file);
    
    // 如果列表为空，显示提示
    if (lv_obj_get_child_cnt(ui_AccountList) == 0) {
        lv_obj_t *empty_text = lv_list_add_text(ui_AccountList, "暂无账号");
        lv_obj_set_style_text_font(empty_text, &ui_font_Font1, LV_PART_MAIN);
    }
}

// 从文件中删除账号
// 返回值:true = 确实删掉了一条记录;false = 没找到该账号(或文件打不开)
bool delete_account_from_file(const char * account) {
    if (account == NULL || account[0] == '\0') {
        return false;
    }

    FILE * src = fopen(FILE_PATH, "r");
    FILE * temp = fopen("/spiffs/temp.txt", "w");
    
    if (!src || !temp) {
        ESP_LOGE("SPIFFS", "无法打开文件");
        if (src) fclose(src);
        if (temp) fclose(temp);
        return false;
    }
    
    char line[MAX_ACCOUNT_LENGTH + MAX_PASSWORD_LENGTH + 2];
    int removed = 0;
    while (fgets(line, sizeof(line), src)) {
        // 比对时同样只取逗号前的账号部分（用整行比对永远不可能相等）
        char existing_account[MAX_ACCOUNT_LENGTH] = {0};
        const char *comma = strchr(line, ',');
        size_t name_len = comma ? (size_t)(comma - line) : strcspn(line, "\r\n");
        if (name_len >= MAX_ACCOUNT_LENGTH) {
            name_len = MAX_ACCOUNT_LENGTH - 1;
        }
        memcpy(existing_account, line, name_len);
        existing_account[name_len] = '\0';

        if (strcmp(existing_account, account) == 0) {
            removed++;              // 命中要删除的账号：这一行不写进临时文件
        } else {
            fputs(line, temp);      // 其余账号原样保留
        }
    }
    
    fclose(src);
    fclose(temp);
    
    // 删除原文件并将临时文件重命名
    remove(FILE_PATH);
    rename("/spiffs/temp.txt", FILE_PATH);

    ESP_LOGI("SPIFFS", "删除账号 %s: %s", account, (removed > 0) ? "成功" : "未找到");

    delete_save_account("acc");
    delete_save_account("pwd");

    return (removed > 0);
}

// 退出按钮事件
void ui_event_exitbtu2(lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        char account[MAX_ACCOUNT_LENGTH] = {0};
        char password[MAX_PASSWORD_LENGTH] = {0};
        if(read_text_from_nvs(account, MAX_ACCOUNT_LENGTH, "acc") == ESP_OK)
        {
            if(read_text_from_nvs(password, MAX_PASSWORD_LENGTH, "pwd") == ESP_OK)
            {
                lv_textarea_set_text(ui_zhanghao, account);
                lv_textarea_set_text(ui_mima, password);
                lv_obj_add_state(ui_jizhu, LV_STATE_CHECKED); 
            }
        }
        _ui_screen_change(&ui_Screen1, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_Screen1_screen_init);
    }
}

// 初始化账号管理界面
void ui_Screen4_screen_init(void) {
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_exitbtu2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_exitbtu2, 80);
    lv_obj_set_height(ui_exitbtu2, 40);
    lv_obj_set_x(ui_exitbtu2, 350);
    lv_obj_set_y(ui_exitbtu2, -200);
    lv_obj_set_align(ui_exitbtu2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_exitbtu2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_exitbtu2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_exitbtu2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "退出");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 0);
    lv_obj_set_y(ui_Label9, -200);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "账号管理界面");
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_deletebtu1 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_deletebtu1, 80);
    lv_obj_set_height(ui_deletebtu1, 40);
    lv_obj_set_x(ui_deletebtu1, 350);
    lv_obj_set_y(ui_deletebtu1, 200);
    lv_obj_set_align(ui_deletebtu1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_deletebtu1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_deletebtu1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label11 = lv_label_create(ui_deletebtu1);
    lv_obj_set_width(ui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label11, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label11, "删除");
    lv_obj_set_style_text_font(ui_Label11, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);

    // 创建账号列表
    init_selected_style();
    ui_AccountList = lv_list_create(ui_Screen4);
    lv_obj_set_size(ui_AccountList, 300, 300);  // 设置列表大小
    lv_obj_align(ui_AccountList, LV_ALIGN_CENTER, 0, 0);  // 居中对齐
    
    // 设置列表样式
    lv_obj_set_style_bg_color(ui_AccountList, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_AccountList, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_AccountList, lv_color_hex(0xCCCCCC), LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // 加载账号到列表
    load_accounts_to_list();
    
    // 添加事件回调
    lv_obj_add_event_cb(ui_exitbtu2, ui_event_exitbtu2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_deletebtu1, delete_btn_click_event, LV_EVENT_CLICKED, NULL);
}

// 销毁界面
void ui_Screen4_screen_destroy(void) {
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // 清理列表项 user_data（在删除对象前释放）
    if (ui_AccountList) {
        uint32_t cnt = lv_obj_get_child_cnt(ui_AccountList);
        for (uint32_t i = 0; i < cnt; i++) {
            lv_obj_t * child = lv_obj_get_child(ui_AccountList, i);
            void * data = lv_obj_get_user_data(child);
            if (data) {
                lv_mem_free(data);
                lv_obj_set_user_data(child, NULL);
            }
        }
    }

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_exitbtu2 = NULL;
    ui_Label10 = NULL;
    ui_Label9 = NULL;
    ui_deletebtu1 = NULL;
    ui_Label11 = NULL;
    ui_AccountList = NULL;
    selected_item = NULL;
    selected_account[0] = '\0';
}