// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN4_H
#define UI_SCREEN4_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen4
extern void ui_Screen4_screen_init(void);
extern void ui_Screen4_screen_destroy(void);
extern lv_obj_t * ui_Screen4;
extern void ui_event_exitbtu2(lv_event_t * e);
extern lv_obj_t * ui_exitbtu2;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_deletebtu1;
extern lv_obj_t * ui_Label11;
extern lv_obj_t * ui_AccountList;
extern lv_obj_t * selected_item;
typedef void (*ConfirmCallback)(bool confirmed, void * user_data);
extern ConfirmCallback g_confirm_callback;
extern void * g_confirm_user_data;
extern void list_item_click_event(lv_event_t * e);
extern void delete_btn_click_event(lv_event_t * e);
extern void delete_confirm_callback(bool confirmed, void *user_data);
extern void load_accounts_to_list();
// 返回值:true = 确实删掉了一条记录;false = 没找到该账号
extern bool delete_account_from_file(const char * account);
extern void confirm_box_event_handler(lv_event_t * e);
extern void show_confirm_box_nonblock(const char * title, const char * message, ConfirmCallback callback, void * user_data);
extern void init_selected_style();
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

