// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_login;
extern void ui_event_zhanghao(lv_event_t * e);
extern lv_obj_t * ui_zhanghao;
extern void ui_event_mima(lv_event_t * e);
extern lv_obj_t * ui_mima;
extern lv_obj_t * ui_Label1;
extern void ui_event_loginbtu1(lv_event_t * e);
extern lv_obj_t * ui_loginbtu1;
extern lv_obj_t * ui_Label2;
extern void ui_event_registerbtu1(lv_event_t * e);
extern lv_obj_t * ui_registerbtu1;
extern lv_obj_t * ui_Label3;
extern void ui_event_tongyi(lv_event_t * e);
extern lv_obj_t * ui_tongyi;
extern lv_obj_t * ui_jizhu;
extern void ui_event_Keyboard1(lv_event_t * e);
extern lv_obj_t * ui_Keyboard1;
extern void ui_event_managebtu1(lv_event_t * e);
extern lv_obj_t * ui_managebtu1;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

