// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}

void ui_destroy(void)
{
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
    ui_Screen3_screen_destroy();
    ui_Screen4_screen_destroy();
}

// 消息框事件处理函数
static void msgbox_event_handler(lv_event_t * e) {
    // 获取按钮矩阵对象
    lv_obj_t * btnm = lv_event_get_target(e);
    
    // 通过按钮矩阵获取消息框对象
    lv_obj_t * msgbox = lv_obj_get_parent(btnm);
    
    // 关闭消息框
    lv_msgbox_close(msgbox);
}

// 显示消息框的函数
void show_message_box(const char *title, const char *message) {
    static const char * btns[] = {"确定", ""};
    lv_obj_t * mbox = lv_msgbox_create(NULL, title, message, btns, true);

    // 设置消息盒子使用的字体
    lv_obj_set_style_text_font(mbox, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(mbox);

    // 添加事件回调处理按钮点击
    lv_obj_add_event_cb(mbox, msgbox_event_handler, LV_EVENT_CLICKED, NULL);
}
