// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"
#include "../lvgl_port.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
lv_obj_t * ui____initial_actions0;

// 鼠标光标对象(全局,可在外部引用)
lv_obj_t * ui_cursor = NULL;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);

    // 初始化鼠标光标:在顶层创建一个圆形指示器,绑定到触摸输入设备
    // LVGL 会在触摸按下/移动时自动更新光标位置(点击哪里显示哪里,滑动也跟随)
    ui_cursor = lv_obj_create(lv_layer_top());
    lv_obj_clear_flag(ui_cursor, LV_OBJ_FLAG_SCROLLABLE);   // 光标本身不可滚动
    lv_obj_set_size(ui_cursor, 16, 16);                      // 光标尺寸 16x16
    lv_obj_set_style_radius(ui_cursor, LV_RADIUS_CIRCLE, LV_PART_MAIN | LV_STATE_DEFAULT);  // 圆形
    lv_obj_set_style_bg_opa(ui_cursor, LV_OPA_80, LV_PART_MAIN | LV_STATE_DEFAULT);         // 半透明填充
    lv_obj_set_style_bg_color(ui_cursor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);  // 黑色填充
    lv_obj_set_style_border_color(ui_cursor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);  // 白色边框
    lv_obj_set_style_border_width(ui_cursor, 2, LV_PART_MAIN | LV_STATE_DEFAULT);            // 边框宽 2
    lv_obj_set_style_outline_color(ui_cursor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_cursor, 1, LV_PART_MAIN | LV_STATE_DEFAULT);           // 外描边增强对比

    // 将光标绑定到触摸输入设备(LVGL 会自动跟随触摸点)
    if (g_lvgl_indev != NULL) {
        lv_indev_set_cursor(g_lvgl_indev, ui_cursor);
    }

    // 初始位置设到屏幕中心(LVGL_PORT_H_RES/V_RES 在 lvgl_port.h 中定义)
    lv_obj_set_pos(ui_cursor, LVGL_PORT_H_RES / 2 - 8, LVGL_PORT_V_RES / 2 - 8);

    ui_Screen0_screen_init();
    ui_Screen1_screen_init();
    ui_Screen2_screen_init();
    ui_Screen3_screen_init();
    ui_Screen4_screen_init();
    ui_Screen5_screen_init();
    // 注意:ui_Screen6 不在开机时预创建(占用 PSRAM 约 300KB)
    // 按需从桌面"画图"图标跳转时由 _ui_screen_change 自动调用 init
    ui____initial_actions0 = lv_obj_create(NULL);
    // 开机先显示启动界面;进度条走满后由 ui_Screen0 自己的定时器切到登录页
    lv_disp_load_scr(ui_Screen0);
}

void ui_destroy(void)
{
    ui_Screen0_screen_destroy();
    ui_Screen1_screen_destroy();
    ui_Screen2_screen_destroy();
    ui_Screen3_screen_destroy();
    ui_Screen4_screen_destroy();
    ui_Screen5_screen_destroy();
    ui_Screen6_screen_destroy();
}

// 消息框事件处理函数
static void msgbox_event_handler(lv_event_t * e) {
    // current_target 才是注册回调的消息框对象本身
    lv_obj_t * msgbox = lv_event_get_current_target(e);
    
    // 关闭消息框
    lv_msgbox_close(msgbox);
}

// 显示消息框的函数
void show_message_box(const char *title, const char *message) {
    static const char * btns[] = {"确定", ""};
    lv_obj_t * mbox = lv_msgbox_create(NULL, title, message, btns, true);

    // 1. 设置标题字体（自定义中文字体）
    lv_obj_t * title_label = lv_msgbox_get_title(mbox);
    if (title_label) {
        lv_obj_set_style_text_font(title_label, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    // 2. 设置消息内容字体（自定义中文字体）
    lv_obj_t * text_label = lv_msgbox_get_text(mbox);
    if (text_label) {
        lv_obj_set_style_text_font(text_label, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    // 3. 设置按钮矩阵字体（同样使用自定义中文字体，保证“确定”不乱码，同时若字体包含符号，关闭按钮也正常）
    lv_obj_t * btns_obj = lv_msgbox_get_btns(mbox);
    if (btns_obj) {
        lv_obj_set_style_text_font(btns_obj, &ui_font_Font1, LV_PART_MAIN | LV_STATE_DEFAULT);
    }

    // 消息框居中
    lv_obj_center(mbox);

    // 添加事件回调（点击按钮关闭）
    lv_obj_add_event_cb(mbox, msgbox_event_handler, LV_EVENT_CLICKED, NULL);
}
