// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_Screen0.h"
#include "screens/ui_Screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"
#include "screens/ui_Screen5.h"
#include "screens/ui_Screen6.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// 光标对象外部声明
extern lv_obj_t * ui_cursor;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_1984903667);    // assets/R-Cpink.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);
void show_message_box(const char *title, const char *message);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif